apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-10-16T17:59:31Z"
  labels:
    run: airflow-postgres-proxy
  name: airflow-postgres-proxy-service
  namespace: default
  resourceVersion: "1180"
  selfLink: /api/v1/namespaces/default/services/airflow-postgres-proxy-service
  uid: b495a324-f03e-11e9-b753-42010a8000a5
spec:
  ports:
    - port: 3307
      protocol: TCP
      targetPort: 3307
  selector:
    run: airflow-postgres-proxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
